name: main
on: push
# Пример для проекта на Node.js
jobs:
  build: # имя взято для примера
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v3
      # Устанавливаем Node.js
      - uses: actions/setup-node@v3
	with:
          node-version: [18]
          cache: 'npm'
      - run: make setup
      - run: make test
      - run: make lint
